import 'package:coffe/model/product.dart';
import 'package:flutter/material.dart' show Icon, Icons;

class Provider {
  static List<Product> products = [
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_maker_outlined,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
    Product(
      icon: Icons.coffee_maker,
      name: 'Caffee Latte',
      price: 28,
      description: 'Latte with milk',
    ),
    Product(
      icon: Icons.food_bank,
      name: 'Mocha',
      price: 7,
      description: 'Original Mocha',
    ),
    Product(
      icon: Icons.coffee_maker_outlined,
      name: 'Macchiato Coffe',
      price: 9,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Milk Drink',
      price: 12,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Hot Chocolate',
      price: 0.99,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Caffee Latte',
      price: 28,
      description: 'Latte with milk',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Mocha',
      price: 7,
      description: 'Original Mocha',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Macchiato Coffe',
      price: 9,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Milk Chick',
      price: 12,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Hot Chocolate',
      price: 0.99,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Caffee Latte',
      price: 28,
      description: 'Latte with milk',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Mocha',
      price: 7,
      description: 'Original Mocha',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Macchiato Coffe',
      price: 9,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Milk Drink',
      price: 12,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Hot Chocolate',
      price: 0.99,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Caffee Latte',
      price: 28,
      description: 'Latte with milk',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Mocha',
      price: 7,
      description: 'Original Mocha',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Macchiato Coffe',
      price: 9,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Milk Chick',
      price: 12,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Hot Chocolate',
      price: 0.99,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Caffee Latte',
      price: 28,
      description: 'Latte with milk',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Mocha',
      price: 7,
      description: 'Original Mocha',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Macchiato Coffe',
      price: 9,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Milk Drink',
      price: 12,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Hot Chocolate',
      price: 0.99,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Caffee Latte',
      price: 28,
      description: 'Latte with milk',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Mocha',
      price: 7,
      description: 'Original Mocha',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Macchiato Coffe',
      price: 9,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Milk Chick',
      price: 12,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Hot Chocolate',
      price: 0.99,
      description: 'Macchiato Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'French Coffe',
      price: 37,
      description: 'Original Coffe',
    ),
    Product(
      icon: Icons.coffee_rounded,
      name: 'Egyptain Tea',
      price: 16,
      description: 'Pharonic Tea',
    ),
  ];
}
